dataset:
    method: from_cassandra
    params:
        db_table: shohel.refined_stock_data
        stock_symbol: AAPL

        # FORMAT: %Y-%m-%d %H:%M:%S
        timestamps:
            start: '2019-01-01 00:00:00'
            end: '2019-01-10 00:00:00'

    # EXPECTED ROW SCHEMA
    expected_schema:
        symbol: str
        timestamp: str
        open: float
        close: float
        high: float
        low: float
        volume: int

#######################################################################################
#######################################################################################

features:

    # ADD STOCHASTIC K FEATURE
    -   name: stochastic_k
        params:
            window_size: 5
            output_column: sk5

    # SHIFT CLOSE COLUMN FORWARD BY 14 STEPS
    # THIS WILL BE THE TARGET COLUMN FOR MODEL TRAINING
    -   name: shift_column
        params:
            target_column: close
            shift_by: 14
            output_column: shifted_close

#######################################################################################
#######################################################################################

training:

    # WHAT COLUMNS TO USE FOR FEATURES
    feature_columns:
        - open
        - close
        - high
        - low
        - volume
        - sk5

    # WHAT COLUMN DO WE WANT TO PREDICT
    label_column: shifted_close

    # HOW SHOULD THE DATASET BE SEGMENTED?
    segmentation:
        method: standard_ttv
        params:
            sequence_ratio:
                - train: 0.75
                - test: 0.15
                - validate: 0.1

    # WHAT SCALAR SHOULD WE USE?
    scaler:
        name: standard_scaler
        params: {}

    # WHAT MODEL SHOULD WE USE?
    model:
        # name: xg_boost_regression
        # params:
        #     n_estimators: 5
        #     max_depth: 2
        #     learning_rate: 0.1
        #     subsample: 0.8
        #     cross_validation:
        #         min: 1e-3
        #         max: 1e2
        # name: linear_regression
        # params: {}
        # name: xg_boost
        # params:
        #     n_estimators: 5
        #     max_depth: 2
        #     learning_rate: 0.1
        #     subsample: 0.8
        # name: svr
        # params:
        #     C: 1.0
        #     epsilon: 0.1
        #     kernel: rbf
        #     n_splits: 3
        # name: cat_boost
        # params:
        #     iterations: 100
        #     learning_rate: 0.1
        #     depth: 6
        #     l2_leaf_reg: 3.0
        #     loss_function: RMSE
        name: mlp_regressor
        params:
            hidden_layer_sizes: [200, 100, 50]
            activation: relu
            solver: adam
            alpha: 0.001
            learning_rate: adaptive
            max_iter: 1000
            random_state: 42
            early_stopping: true
            validation_fraction: 0.1
    # model:
    #     name: linear_regression
    #     params: {}